### ISSUE TITLE
migrate to angular

### ISSUE THREAD

**Issue by helio-frota** [aeshell/nanook#120]

**Comment by eprogramming** [comment]
now the current situation of our javascript is not good for maintenance
trying to figure out the approach with websockets
the good the bad and the ugly parts...
this can also enable websockets wf-swarm support and try to improve Or break this app for a long period of time..

**Comment by emag** [comment]
> this can also enable websockets wf-swarm support

wildfly-swarm-jaxrs includes websocket api, so you can already use it.

I've just created a WebSocket sample(undertow example copy).

https://github.com/emag/wildfly-swarm-quickstarts/tree/master/websocket

**Comment by eprogramming** [comment]
great, we can try this:
1. move to angular
2. change the model 'request - response' to websocket

going to create another issue

**Comment by helio-frota** [comment]
closing the issues, moving to undertowjs fraction of wildfly-swarm + jqueryTerminal for the front-end.
