### ISSUE TITLE
expose the aesh history with rest from wildfly-swarm

### ISSUE THREAD

**Issue by eprogramming** [aeshell/nanook#122]
something like 
http://localhost:8080/history
output as json

**Comment by eprogramming** [comment]
This one is almost the 'same' of #123 but here we going to deal with aesh command history , to integrate aesh + wildfly-swarm + jax-rs showing all executed commands

**Comment by emag** [comment]
Hi, I have a question.

What kind of info can I get by the history api ? I guess It is only users own history?

If so, since now Nanook doesn't have user authentication function, it can't distinguish each user in server side. Or are you planning to use some client(JavaScript) api such as localStorage?

**Comment by eprogramming** [comment]
@emag the plan is try to show the Aesh history
Aesh is a shell 100% java and nanook is using it to run the commands like 'ls, mv, cat, ...'

**Comment by eprogramming** [comment]
> What kind of info can I get by the history api ?

the history of executed commands on the aesh

**Comment by emag** [comment]
Oh, Ok! sorry, I'm new to Aesh.

**Comment by eprogramming** [comment]
@emag no problem : ]
you can try to create the jax-rs parte wdyt ?

**Comment by eprogramming** [comment]
while i try to get the history from aesh

**Comment by emag** [comment]
> you can try to create the jax-rs parte wdyt ?

It means NanookServlet to JAX-RS ? Or, https://github.com/aeshell/nanook/issues/123 ?

**Comment by eprogramming** [comment]
means create another class , maybe 'NanookRest'
and config a wildfly-swarm JAX-RS fraction, so that we going to have static + sevlet + jax-rs on running app.

**Comment by emag** [comment]
I got it and I'll create empty methods(history, log) in NanookRest for now .

**Comment by eprogramming** [comment]
Awesome !

**Comment by eprogramming** [comment]
so if you catch any issue or bug, you have a 'running app' to show to the wf-swarm folks.
because is more 'easy to have a project' to explore more a tecnology ofc than an example, i mean we can try more unusual things on a running project than an example.

**Comment by emag** [comment]
Yes,  indeed :)

**Comment by eprogramming** [comment]
bit info:

[Æsh](http://aeshell.github.io/)
`
1. Æsh is a Java API that provides functionality to write command-based programs in a terminal-independent manner. `
`2. Æsh is used on jboss-forge, wildfly-core , artificer and others products`

Nanook
`1. nanook name means nothing, is the name of on of my dogs`
`2. the first goal is to explore Æsh API and features to try to contribute with feedback and pull requests like this project: ` [mterm](https://github.com/aeshell/mterm)
`3. second goal is to do the same for wildfly-swarm`
`4. for now is not a real tool to run in production environment, but to put unusual ideas together and have fun trying make it work`

**Comment by emag** [comment]
Ok, I got it. interesting!

**Comment by emag** [comment]
I filed it. https://github.com/aeshell/nanook/issues/126

**Comment by emag** [comment]
I have a question about history api.

Now the api serves `.aesh_history` and the history file is placed in the machine where Nanook runs. This means history is shared with several clients, machines. Is this spec ok ?

**Comment by eprogramming** [comment]
afaik aesh was not designed to this.
you can imagine nanook as a 'gnome-terminal' or 'xfce4-terminal' app that uses a shell.
is [mterm](https://github.com/aeshell/mterm/blob/master/README.md) but running from a browser
that means totally unusual app, so if we publish this on the cloud for instance, if you run a command I (another user) can see your executed command.

in this case

> Is this spec ok ?

yes

**Comment by emag** [comment]
> that means totally unusual app

haha :) OK! It'd also be a shell share service.

**Comment by eprogramming** [comment]
great, so that you found another 'goal' to this project.

now we have 3:
* explore aesh and try to give feedbacks and/or pull requests
* explore wildfly-swarm and try to give feedbacks and/or pull requests
* a shell share service
