### ISSUE TITLE
expose wildfly-swarm logs with rest 

### ISSUE THREAD

**Issue by eprogramming** [aeshell/nanook#123]

**Comment by eprogramming** [comment]
Ok, the fun is show current logs of wildfly-swarm by using a jax-rs 
this app is now a wildfly-swarm :  'static content' + 'servlet' example of running app 

and now we going to add  jax-rs in to it to make the things more cool

**Comment by eprogramming** [comment]
ok this one will be tricky since if we redirect the log (stdout) to memory can expose the data but lost the console log. 
maybe if we enable file log whe can read the file and keep with console (stdout) log.. since the issue #122 we just read a file ... 

what do you think ?

**Comment by eprogramming** [comment]
how enable both console log and file log  on wf-swarm ?

**Comment by emag** [comment]
Now wf-swarm supports only console-handler. so, if you want wf-swarm to log to a file, it needs some file-handler support.

Or, maybe you can snatch System.out for `tee`(console and file).

1. Add TeePrintStream class like
http://www.java2s.com/Code/Java/File-Input-Output/TeePrintStreamteesallPrintStreamoperationsintoafileratherliketheUNIXtee1command.htm
2. Add `System.setOut(new TeePrintStream(System.out, "console.log", true))` in main().
3. And, you need to close TeePrintStream. maybe in Shutdownhook.

``` java
public class Main {

    public static void main(String... args) throws Exception {

        System.setOut(new TeePrintStream(System.out, "console.log", true));

        // container configuration.
        Container container = new Container();
        ...
    }
}
```

**Comment by eprogramming** [comment]
good information @emag thanks.

> Now wf-swarm supports only console-handler

So that means we going to open an issue on wf-swarm right ?

**Comment by emag** [comment]
Yes. I've checked your wf-swarm issue. Of cource, It is helpful for others :)

**Comment by eprogramming** [comment]
+1

**Comment by eprogramming** [comment]
@emag awesome job ! Thanks

![a](https://cloud.githubusercontent.com/assets/6443576/8367067/75adc0c6-1b71-11e5-91a8-4d42833ef6cc.png)
