### ISSUE TITLE
crontab support

### ISSUE THREAD

**Issue by emag** [aeshell/nanook#126]
from https://github.com/aeshell/nanook/issues/122

@eprogramming wrote

> Maybe since we are running commands , maybe we can try todo behavior like 'crontab' : D
to run commands from time to time ... wdyt ?
> for instance a EJB timer to run ls command 5 and 5 minutes

* Use EJB Timer, some server push API(like WebSockts, Server-Sent Events)
 * **(Blocker)** Unfortunately, now WF-Swarm does [not support EJB](https://github.com/wildfly-swarm/wildfly-swarm/issues/59).
 * Although Java EE 7 spec doesn't include Server-Sent Events, but Undertow supports it.
    * https://github.com/undertow-io/undertow/tree/1.2.7.Final/examples/src/main/java/io/undertow/examples/sse

**Comment by helio-frota** [comment]
using undertowjs fraction of wildfly-swarm and jquery terminal for the front-end.
try just keep this integration working ^
